/**
 * Playlist Management Module
 * Handles automatic and manual playlist creation
 */

class PlaylistManager {
  constructor() {
    this.profileManager = profileManager;
    this.dataManager = dataManager;
    this.init();
  }

  /**
   * Initialize playlist manager
   */
  init() {
    this.generateArtistPlaylists();
  }

  /**
   * Generate playlists automatically by artist
   */
  generateArtistPlaylists() {
    const user = this.profileManager.getCurrentUser();
    const songs = this.dataManager.getSongs();
    const artists = this.dataManager.getArtists();
    
    // Group songs by artist
    const artistSongs = {};
    songs.forEach(song => {
      if (!artistSongs[song.artist]) {
        artistSongs[song.artist] = [];
      }
      artistSongs[song.artist].push(song.id);
    });

    // Create playlists for each artist
    const artistPlaylists = [];
    artists.forEach(artist => {
      const songIds = artistSongs[artist.name] || [];
      if (songIds.length > 0) {
        artistPlaylists.push({
          id: `artist-${artist.id}`,
          title: `${artist.name} - All Songs`,
          description: `All songs by ${artist.name}`,
          cover: artist.image,
          artist: artist.name,
          songs: songIds,
          type: 'artist',
          autoGenerated: true
        });
      }
    });

    // Store in user data
    user.artistPlaylists = artistPlaylists;
    this.profileManager.currentUser = user;
    this.profileManager.saveUser();

    return artistPlaylists;
  }

  /**
   * Get artist playlists
   */
  getArtistPlaylists() {
    const user = this.profileManager.getCurrentUser();
    return user.artistPlaylists || [];
  }

  /**
   * Create manual playlist
   */
  createPlaylist(name, description = '', cover = '', songIds = []) {
    const user = this.profileManager.getCurrentUser();
    const playlists = user.playlists || [];
    
    const newPlaylist = {
      id: `playlist-${Date.now()}`,
      title: name,
      description: description,
      cover: cover || 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
      songs: songIds,
      type: 'playlist',
      autoGenerated: false,
      createdAt: new Date().toISOString()
    };

    playlists.push(newPlaylist);
    user.playlists = playlists;
    this.profileManager.currentUser = user;
    this.profileManager.saveUser();

    return newPlaylist;
  }

  /**
   * Get all user playlists
   */
  getUserPlaylists() {
    const user = this.profileManager.getCurrentUser();
    return user.playlists || [];
  }

  /**
   * Add song to playlist
   */
  addSongToPlaylist(playlistId, songId) {
    const user = this.profileManager.getCurrentUser();
    const playlists = user.playlists || [];
    const playlist = playlists.find(p => p.id === playlistId);

    if (playlist && !playlist.songs.includes(songId)) {
      playlist.songs.push(songId);
      this.profileManager.currentUser = user;
      this.profileManager.saveUser();
      return true;
    }
    return false;
  }

  /**
   * Remove song from playlist
   */
  removeSongFromPlaylist(playlistId, songId) {
    const user = this.profileManager.getCurrentUser();
    const playlists = user.playlists || [];
    const playlist = playlists.find(p => p.id === playlistId);

    if (playlist) {
      const index = playlist.songs.indexOf(songId);
      if (index > -1) {
        playlist.songs.splice(index, 1);
        this.profileManager.currentUser = user;
        this.profileManager.saveUser();
        return true;
      }
    }
    return false;
  }

  /**
   * Delete playlist
   */
  deletePlaylist(playlistId) {
    const user = this.profileManager.getCurrentUser();
    const playlists = user.playlists || [];
    const filtered = playlists.filter(p => p.id !== playlistId);
    
    user.playlists = filtered;
    this.profileManager.currentUser = user;
    this.profileManager.saveUser();
    return true;
  }

  /**
   * Get playlist by ID
   */
  getPlaylistById(playlistId) {
    const user = this.profileManager.getCurrentUser();
    const allPlaylists = [
      ...(user.playlists || []),
      ...(user.artistPlaylists || [])
    ];
    return allPlaylists.find(p => p.id === playlistId);
  }
}

// Export singleton instance
const playlistManager = new PlaylistManager();

